max-gamma = 100

profile {
    time = 6:00
    identity = true
}


# 21:00 - 21:59
profile {
    time = 21:00
    gamma = 0.9
}
profile {
    time = 21:30
    gamma = 0.8
}


# 22:00 - 22:59
profile {
    time = 22:00
    gamma = 0.7
}
profile {
    time = 22:30
    gamma = 0.6
}


# fuck you, go sleep zone™
profile {
    time = 23:00
    gamma = 0.5
}
