# Set C-a as default prefix (GNU Screen)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Start windows & panes index at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete
set-option -g renumber-windows on

# Statusbar
#set -g status-style 'bg=#474747 fg=#ffffff'
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g status-right ""

# Don't confirm KILLING :)
bind x kill-pane
