font_family JetBrainsMonoNL Nerd Font Mono
font_features NotoColorEmoji

font_size 10

tab_bar_style powerline
tab_title_template {index}:{title}
tab_bar_background #000000

active_tab_foreground   #ffffff
active_tab_background   #000000
inactive_tab_foreground #999999
inactive_tab_background #000000

foreground #ffffff
background #000000
background_opacity 0.4

confirm_os_window_close 0
